services:
  redirector:
    build: .
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirector.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.redirector.entrypoints=websecure"
      - "traefik.http.routers.redirector.tls.certresolver=letsencrypt"
      - "traefik.http.services.redirector.loadbalancer.server.port=${PORT}"

networks:
  traefik-net:
    external: true
