services:
  redirector:
    build: .
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirector.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.redirector.entrypoints=websecure"
      - "traefik.http.routers.redirector.tls.certresolver=letsencrypt"
      - "traefik.http.services.redirector.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
